/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#4648d4",
        "surface-container-highest": "#dae2fd",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#930013",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#07006c",
        "surface-bright": "#faf8ff",
        "primary-container": "#6063ee",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#283044",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#410004",
        "tertiary-container": "#da3437",
        "on-surface": "#131b2e",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        outline: "#767586",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        "on-tertiary-container": "#fffbff",
        "outline-variant": "#c7c4d7",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        "surface-dim": "#d2d9f4",
        surface: "#faf8ff",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container": "#eaedff",
        "surface-container-low": "#f2f3ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#ffdad7",
        "inverse-primary": "#c0c1ff",
        tertiary: "#b61722",
        "surface-container-high": "#e2e7ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface-variant": "#464554",
        "inverse-on-surface": "#eef0ff",
        "surface-tint": "#494bd6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        secondary: "#006c49",
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e1e0ff",
        background: "#faf8ff",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
