
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9ff",
        "outline": "#727785",
        "surface-container-highest": "#e1e2ec",
        "surface-variant": "#e1e2ec",
        "primary-fixed-dim": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        "outline-variant": "#c2c6d6",
        "inverse-primary": "#adc6ff",
        "on-tertiary-fixed-variant": "#723600",
        "tertiary-container": "#b75b00",
        "secondary-fixed-dim": "#c0c7d6",
        "on-surface": "#191b23",
        "surface-tint": "#005ac2",
        "surface-container-high": "#e6e7f2",
        "primary-container": "#2170e4",
        "on-secondary-fixed-variant": "#404754",
        "secondary": "#585f6c",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#311400",
        "on-primary-container": "#fefcff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#d8d9e3",
        "on-error-container": "#93000a",
        "secondary-container": "#dce2f3",
        "on-primary-fixed": "#001a42",
        "surface-container-low": "#f2f3fd",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#191b23",
        "inverse-surface": "#2e3038",
        "on-surface-variant": "#424754",
        "on-secondary-container": "#5e6572",
        "background": "#f9f9ff",
        "secondary-fixed": "#dce2f3",
        "tertiary-fixed": "#ffdcc6",
        "surface-container": "#ecedf7",
        "tertiary": "#924700",
        "inverse-on-surface": "#eff0fa",
        "on-tertiary-container": "#fffbff",
        "primary": "#0058be",
        "on-secondary-fixed": "#151c27",
        "error": "#ba1a1a"
      },
      spacing: {
        "sidebar-width": "240px",
        "stack-lg": "24px",
        "header-height": "64px",
        "gutter": "24px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

