/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e0e3e5",
        primary: "#c0c1ff",
        "surface-dim": "#13131b",
        "on-error": "#690005",
        "on-tertiary": "#4f2500",
        "on-surface-variant": "#c7c4d7",
        "on-surface": "#e4e1ed",
        "on-secondary": "#2d3133",
        "tertiary-container": "#d97721",
        error: "#ffb4ab",
        "on-secondary-fixed": "#191c1e",
        background: "#13131b",
        "inverse-on-surface": "#303038",
        "on-secondary-fixed-variant": "#444749",
        "primary-container": "#8083ff",
        "surface-container-high": "#292932",
        "surface-bright": "#393841",
        "secondary-container": "#464a4b",
        "on-tertiary-fixed": "#301400",
        surface: "#13131b",
        "on-tertiary-fixed-variant": "#703700",
        "surface-container": "#1f1f27",
        "on-primary": "#1000a9",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#ffdcc5",
        "inverse-primary": "#494bd6",
        outline: "#908fa0",
        "tertiary-fixed-dim": "#ffb783",
        "outline-variant": "#464554",
        "on-primary-fixed": "#07006c",
        "on-secondary-container": "#b6b9bb",
        "surface-tint": "#c0c1ff",
        "surface-container-low": "#1b1b23",
        "on-tertiary-container": "#452000",
        "inverse-surface": "#e4e1ed",
        secondary: "#c4c7c9",
        "primary-fixed": "#e1e0ff",
        "surface-container-highest": "#34343d",
        "on-primary-container": "#0d0096",
        "on-background": "#e4e1ed",
        "surface-container-lowest": "#0d0d15",
        "secondary-fixed-dim": "#c4c7c9",
        "on-error-container": "#ffdad6",
        tertiary: "#ffb783",
        "primary-fixed-dim": "#c0c1ff",
        "surface-variant": "#34343d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        card_padding: "20px",
        sidebar_width: "260px",
        container_gap: "24px",
        gutter: "16px",
        base_unit: "4px",
        header_height: "64px",
      },
      fontFamily: {
        "display-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "code-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "display-lg-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
