import logging
from sqlalchemy.orm import Session
from server.models import Region

logger = logging.getLogger(__name__)

INDIAN_REGIONS_DATA = [
    # 28 States
    {
        "name": "Andhra Pradesh",
        "capital": "Amaravati",
        "type": "state",
        "region": "Southern India",
        "population": 49506799,
        "official_languages": ["Telugu"],
        "iso_code": "IN-AP",
        "area_sq_km": 162975.0,
        "density_per_sq_km": 304.0,
    },
    {
        "name": "Arunachal Pradesh",
        "capital": "Itanagar",
        "type": "state",
        "region": "North-Eastern India",
        "population": 1383727,
        "official_languages": ["English"],
        "iso_code": "IN-AR",
        "area_sq_km": 83743.0,
        "density_per_sq_km": 17.0,
    },
    {
        "name": "Assam",
        "capital": "Dispur",
        "type": "state",
        "region": "North-Eastern India",
        "population": 31205576,
        "official_languages": ["Assamese"],
        "iso_code": "IN-AS",
        "area_sq_km": 78438.0,
        "density_per_sq_km": 398.0,
    },
    {
        "name": "Bihar",
        "capital": "Patna",
        "type": "state",
        "region": "Eastern India",
        "population": 104099452,
        "official_languages": ["Hindi"],
        "iso_code": "IN-BR",
        "area_sq_km": 94163.0,
        "density_per_sq_km": 1106.0,
    },
    {
        "name": "Chhattisgarh",
        "capital": "Raipur",
        "type": "state",
        "region": "Central India",
        "population": 25545198,
        "official_languages": ["Hindi", "Chhattisgarhi"],
        "iso_code": "IN-CT",
        "area_sq_km": 135192.0,
        "density_per_sq_km": 189.0,
    },
    {
        "name": "Goa",
        "capital": "Panaji",
        "type": "state",
        "region": "Western India",
        "population": 1458545,
        "official_languages": ["Konkani"],
        "iso_code": "IN-GA",
        "area_sq_km": 3702.0,
        "density_per_sq_km": 394.0,
    },
    {
        "name": "Gujarat",
        "capital": "Gandhinagar",
        "type": "state",
        "region": "Western India",
        "population": 60439692,
        "official_languages": ["Gujarati"],
        "iso_code": "IN-GJ",
        "area_sq_km": 196024.0,
        "density_per_sq_km": 308.0,
    },
    {
        "name": "Haryana",
        "capital": "Chandigarh",
        "type": "state",
        "region": "Northern India",
        "population": 25351462,
        "official_languages": ["Hindi"],
        "iso_code": "IN-HR",
        "area_sq_km": 44212.0,
        "density_per_sq_km": 573.0,
    },
    {
        "name": "Himachal Pradesh",
        "capital": "Shimla",
        "type": "state",
        "region": "Northern India",
        "population": 6864602,
        "official_languages": ["Hindi"],
        "iso_code": "IN-HP",
        "area_sq_km": 55673.0,
        "density_per_sq_km": 123.0,
    },
    {
        "name": "Jharkhand",
        "capital": "Ranchi",
        "type": "state",
        "region": "Eastern India",
        "population": 32988134,
        "official_languages": ["Hindi"],
        "iso_code": "IN-JH",
        "area_sq_km": 79716.0,
        "density_per_sq_km": 414.0,
    },
    {
        "name": "Karnataka",
        "capital": "Bengaluru",
        "type": "state",
        "region": "Southern India",
        "population": 61095297,
        "official_languages": ["Kannada"],
        "iso_code": "IN-KA",
        "area_sq_km": 191791.0,
        "density_per_sq_km": 319.0,
    },
    {
        "name": "Kerala",
        "capital": "Thiruvananthapuram",
        "type": "state",
        "region": "Southern India",
        "population": 33406061,
        "official_languages": ["Malayalam"],
        "iso_code": "IN-KL",
        "area_sq_km": 38863.0,
        "density_per_sq_km": 860.0,
    },
    {
        "name": "Madhya Pradesh",
        "capital": "Bhopal",
        "type": "state",
        "region": "Central India",
        "population": 72626809,
        "official_languages": ["Hindi"],
        "iso_code": "IN-MP",
        "area_sq_km": 308245.0,
        "density_per_sq_km": 236.0,
    },
    {
        "name": "Maharashtra",
        "capital": "Mumbai",
        "type": "state",
        "region": "Western India",
        "population": 112374333,
        "official_languages": ["Marathi"],
        "iso_code": "IN-MH",
        "area_sq_km": 307713.0,
        "density_per_sq_km": 365.0,
    },
    {
        "name": "Manipur",
        "capital": "Imphal",
        "type": "state",
        "region": "North-Eastern India",
        "population": 2855794,
        "official_languages": ["Meitei"],
        "iso_code": "IN-MN",
        "area_sq_km": 22327.0,
        "density_per_sq_km": 128.0,
    },
    {
        "name": "Meghalaya",
        "capital": "Shillong",
        "type": "state",
        "region": "North-Eastern India",
        "population": 2966889,
        "official_languages": ["English"],
        "iso_code": "IN-ML",
        "area_sq_km": 22429.0,
        "density_per_sq_km": 132.0,
    },
    {
        "name": "Mizoram",
        "capital": "Aizawl",
        "type": "state",
        "region": "North-Eastern India",
        "population": 1097206,
        "official_languages": ["Mizo", "English"],
        "iso_code": "IN-MZ",
        "area_sq_km": 21081.0,
        "density_per_sq_km": 52.0,
    },
    {
        "name": "Nagaland",
        "capital": "Kohima",
        "type": "state",
        "region": "North-Eastern India",
        "population": 1978502,
        "official_languages": ["English"],
        "iso_code": "IN-NL",
        "area_sq_km": 16579.0,
        "density_per_sq_km": 119.0,
    },
    {
        "name": "Odisha",
        "capital": "Bhubaneswar",
        "type": "state",
        "region": "Eastern India",
        "population": 41974218,
        "official_languages": ["Odia"],
        "iso_code": "IN-OR",
        "area_sq_km": 155707.0,
        "density_per_sq_km": 270.0,
    },
    {
        "name": "Punjab",
        "capital": "Chandigarh",
        "type": "state",
        "region": "Northern India",
        "population": 27743338,
        "official_languages": ["Punjabi"],
        "iso_code": "IN-PB",
        "area_sq_km": 50362.0,
        "density_per_sq_km": 551.0,
    },
    {
        "name": "Rajasthan",
        "capital": "Jaipur",
        "type": "state",
        "region": "North-Western India",
        "population": 68548437,
        "official_languages": ["Hindi", "Rajasthani"],
        "iso_code": "IN-RJ",
        "area_sq_km": 342239.0,
        "density_per_sq_km": 200.0,
    },
    {
        "name": "Sikkim",
        "capital": "Gangtok",
        "type": "state",
        "region": "North-Eastern India",
        "population": 610577,
        "official_languages": ["Nepali", "English"],
        "iso_code": "IN-SK",
        "area_sq_km": 7096.0,
        "density_per_sq_km": 86.0,
    },
    {
        "name": "Tamil Nadu",
        "capital": "Chennai",
        "type": "state",
        "region": "Southern India",
        "population": 72147030,
        "official_languages": ["Tamil"],
        "iso_code": "IN-TN",
        "area_sq_km": 130058.0,
        "density_per_sq_km": 555.0,
    },
    {
        "name": "Telangana",
        "capital": "Hyderabad",
        "type": "state",
        "region": "Southern India",
        "population": 35003674,
        "official_languages": ["Telugu"],
        "iso_code": "IN-TG",
        "area_sq_km": 112077.0,
        "density_per_sq_km": 312.0,
    },
    {
        "name": "Tripura",
        "capital": "Agartala",
        "type": "state",
        "region": "North-Eastern India",
        "population": 3673917,
        "official_languages": ["Bengali", "Kokborok"],
        "iso_code": "IN-TR",
        "area_sq_km": 10491.0,
        "density_per_sq_km": 350.0,
    },
    {
        "name": "Uttar Pradesh",
        "capital": "Lucknow",
        "type": "state",
        "region": "Northern India",
        "population": 199812341,
        "official_languages": ["Hindi"],
        "iso_code": "IN-UP",
        "area_sq_km": 240928.0,
        "density_per_sq_km": 829.0,
    },
    {
        "name": "Uttarakhand",
        "capital": "Dehradun",
        "type": "state",
        "region": "Northern India",
        "population": 10086292,
        "official_languages": ["Hindi"],
        "iso_code": "IN-UT",
        "area_sq_km": 53483.0,
        "density_per_sq_km": 189.0,
    },
    {
        "name": "West Bengal",
        "capital": "Kolkata",
        "type": "state",
        "region": "Eastern India",
        "population": 91276115,
        "official_languages": ["Bengali"],
        "iso_code": "IN-WB",
        "area_sq_km": 88752.0,
        "density_per_sq_km": 1028.0,
    },
    # 8 Union Territories
    {
        "name": "Andaman and Nicobar Islands",
        "capital": "Port Blair",
        "type": "union_territory",
        "region": "Island Territory",
        "population": 380581,
        "official_languages": ["Hindi", "English"],
        "iso_code": "IN-AN",
        "area_sq_km": 8249.0,
        "density_per_sq_km": 46.0,
    },
    {
        "name": "Chandigarh",
        "capital": "Chandigarh",
        "type": "union_territory",
        "region": "Northern India",
        "population": 1055450,
        "official_languages": ["English", "Hindi", "Punjabi"],
        "iso_code": "IN-CH",
        "area_sq_km": 114.0,
        "density_per_sq_km": 9258.0,
    },
    {
        "name": "Dadra and Nagar Haveli and Daman and Diu",
        "capital": "Daman",
        "type": "union_territory",
        "region": "Western India",
        "population": 585764,
        "official_languages": ["Gujarati", "Hindi", "English"],
        "iso_code": "IN-DH",
        "area_sq_km": 603.0,
        "density_per_sq_km": 970.0,
    },
    {
        "name": "Delhi",
        "capital": "New Delhi",
        "type": "union_territory",
        "region": "Northern India",
        "population": 16787941,
        "official_languages": ["Hindi", "English"],
        "iso_code": "IN-DL",
        "area_sq_km": 1484.0,
        "density_per_sq_km": 11320.0,
    },
    {
        "name": "Jammu and Kashmir",
        "capital": "Srinagar",
        "type": "union_territory",
        "region": "Northern India",
        "population": 12267032,
        "official_languages": ["Dogri", "Hindi", "Kashmiri", "Urdu", "English"],
        "iso_code": "IN-JK",
        "area_sq_km": 42241.0,
        "density_per_sq_km": 290.0,
    },
    {
        "name": "Ladakh",
        "capital": "Leh",
        "type": "union_territory",
        "region": "Northern India",
        "population": 274289,
        "official_languages": ["Ladakhi", "Hindi", "English"],
        "iso_code": "IN-LA",
        "area_sq_km": 59146.0,
        "density_per_sq_km": 4.6,
    },
    {
        "name": "Lakshadweep",
        "capital": "Kavaratti",
        "type": "union_territory",
        "region": "Island Territory",
        "population": 64473,
        "official_languages": ["Malayalam", "English"],
        "iso_code": "IN-LD",
        "area_sq_km": 32.0,
        "density_per_sq_km": 2013.0,
    },
    {
        "name": "Puducherry",
        "capital": "Puducherry",
        "type": "union_territory",
        "region": "Southern India",
        "population": 1247953,
        "official_languages": ["Tamil", "English", "French"],
        "iso_code": "IN-PY",
        "area_sq_km": 479.0,
        "density_per_sq_km": 2598.0,
    },
]


def seed_data(db: Session) -> None:
    """Seed regions table with initial data if empty or missing entries."""
    try:
        existing_names = {r.name for r in db.query(Region.name).all()}

        new_regions = []
        for data in INDIAN_REGIONS_DATA:
            if data["name"] not in existing_names:
                new_regions.append(Region(**data))

        if new_regions:
            db.add_all(new_regions)
            db.commit()
            logger.info(f"Seeded {len(new_regions)} new regions into database.")
    except Exception as e:
        db.rollback()
        logger.error(f"Error seeding regions data: {e}")
        raise e
